const mongoose = require('mongoose');
const dotenv = require('dotenv');
const User = require('./models/User');
const Workshop = require('./models/Workshop');
const Category = require('./models/Category');

dotenv.config();

const CATEGORIES = [
  { name: "Pottery", icon: "🏺" },
  { name: "Weaving", icon: "🧵" },
  { name: "Bamboo Craft", icon: "🎋" },
  { name: "Handloom", icon: "🧶" },
  { name: "Wood Carving", icon: "🪵" },
  { name: "Clay Art", icon: "🏺" },
  { name: "Metal Craft", icon: "⛏️" },
  { name: "Basket Weaving", icon: "🧺" },
];

const USERS = [
  {
    name: "Admin User",
    email: "admin@villagecraft.in",
    password: "password123",
    role: "admin",
    village: "New Delhi",
    phone: "9876543210"
  },
  {
    name: "Ramesh Kumawat",
    email: "ramesh@trainer.com",
    password: "password123",
    role: "trainer",
    village: "Jaipur Village",
    district: "Jaipur",
    state: "Rajasthan",
    experience: "15 years",
    rating: 4.8,
    phone: "9123456780",
    skills: ["Pottery", "Clay Art"]
  }
];

const WORKSHOPS = [
  {
    title: "Pottery Basics for Beginners",
    category: "Pottery",
    trainerName: "Ramesh Kumawat",
    location: "Jaipur Village Center",
    district: "Jaipur",
    state: "Rajasthan",
    date: "2025-04-15",
    duration: "4 weeks",
    skillLevel: "Beginner",
    maxParticipants: 12,
    enrolledCount: 0,
    rating: 4.5,
    description: "Learn traditional hand-built pottery techniques passed down through generations. This workshop covers clay preparation, coiling, and basic glazing methods.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Advanced Handloom Weaving",
    category: "Handloom",
    trainerName: "Ramesh Kumawat",
    location: "Pochampally Craft Lane",
    district: "Yadadri",
    state: "Telangana",
    date: "2025-05-10",
    duration: "8 weeks",
    skillLevel: "Advanced",
    maxParticipants: 8,
    enrolledCount: 0,
    rating: 4.8,
    description: "Master the intricate art of Ikkat weaving in the world-famous Pochampally. Focus on complex geometric patterns and natural dyeing.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Bamboo Furniture Making",
    category: "Bamboo Craft",
    trainerName: "Ramesh Kumawat",
    location: "Kukatpally Artisan Hub",
    district: "Hyderabad",
    state: "Telangana",
    date: "2025-04-25",
    duration: "6 weeks",
    skillLevel: "Intermediate",
    maxParticipants: 15,
    enrolledCount: 0,
    rating: 4.6,
    description: "Learn to build sustainable and durable furniture using locally sourced bamboo. Covers harvesting, treatment, and joinery.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Pochampally Ikkat Mastery",
    category: "Weaving",
    trainerName: "Ramesh Kumawat",
    location: "Pochampally Weavers Coop",
    district: "Nalgonda",
    state: "Telangana",
    date: "2025-06-15",
    duration: "10 weeks",
    skillLevel: "Advanced",
    maxParticipants: 10,
    enrolledCount: 0,
    rating: 4.9,
    description: "Soothe your soul with the rhythm of the loom. Learn the ancient tie-dye weaving technique of Ikkat.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Nirmal Toy Making",
    category: "Wood Carving",
    trainerName: "Ramesh Kumawat",
    location: "Nirmal Toy Industry",
    district: "Nirmal",
    state: "Telangana",
    date: "2025-05-12",
    duration: "4 weeks",
    skillLevel: "Beginner",
    maxParticipants: 20,
    enrolledCount: 0,
    rating: 4.7,
    description: "Craft beautiful toys from locally available softwood. Learn the 'Chitra' style of painting and lacquering.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Bidriware Metal Art",
    category: "Metal Craft",
    trainerName: "Ramesh Kumawat",
    location: "Sultan Bazar Workshop",
    district: "Hyderabad",
    state: "Telangana",
    date: "2025-07-10",
    duration: "8 weeks",
    skillLevel: "Advanced",
    maxParticipants: 6,
    enrolledCount: 0,
    rating: 5.0,
    description: "Learn the 14th-century metal handicraft from Hyderabad. Includes casting, engraving, and inlaying silver on blackened alloy.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Cheriyal Scroll Painting",
    category: "Clay Art",
    trainerName: "Ramesh Kumawat",
    location: "Cheriyal Village",
    district: "Warangal",
    state: "Telangana",
    date: "2025-08-20",
    duration: "6 weeks",
    skillLevel: "Intermediate",
    maxParticipants: 12,
    enrolledCount: 0,
    rating: 4.8,
    description: "Paint traditional narrative scrolls using natural dyes. Learn to make the khadi canvas and distinct red backgrounds.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Dokra Tribal Casting",
    category: "Metal Craft",
    trainerName: "Ramesh Kumawat",
    location: "Keshavapur Village",
    district: "Adilabad",
    state: "Telangana",
    date: "2025-09-05",
    duration: "5 weeks",
    skillLevel: "Intermediate",
    maxParticipants: 15,
    enrolledCount: 0,
    rating: 4.6,
    description: "Master the ancient lost-wax casting technique used by the Ojha community for generations.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Warangal Durrie Weaving",
    category: "Weaving",
    trainerName: "Ramesh Kumawat",
    location: "Kothawada Weavers Colony",
    district: "Warangal",
    state: "Telangana",
    date: "2025-04-20",
    duration: "4 weeks",
    skillLevel: "Beginner",
    maxParticipants: 25,
    enrolledCount: 0,
    rating: 4.4,
    description: "Learn to weave traditional cotton durries with distinct geometric patterns and vibrant colors.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Kondapalli Wood Carving",
    category: "Wood Carving",
    trainerName: "Ramesh Kumawat",
    location: "Toy Colony",
    district: "Vijayawada",
    state: "Andhra Pradesh",
    date: "2025-05-30",
    duration: "6 weeks",
    skillLevel: "Intermediate",
    maxParticipants: 12,
    enrolledCount: 0,
    rating: 4.7,
    description: "Carve the famous Kondapalli toys using 'Tella Poniki' wood. Focus on traditional figurines and mythological characters.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Traditional Wood Carving",
    category: "Wood Carving",
    trainerName: "Ramesh Kumawat",
    location: "Saharanpur Wood Hub",
    district: "Saharanpur",
    state: "Uttar Pradesh",
    date: "2025-07-01",
    duration: "10 weeks",
    skillLevel: "Advanced",
    maxParticipants: 6,
    enrolledCount: 0,
    rating: 4.9,
    description: "Intricate wood carving for architectural elements and decor. Learn about wood types, chiseling, and polishing.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Sustainable Basket Weaving",
    category: "Basket Weaving",
    trainerName: "Ramesh Kumawat",
    location: "Medak Artisan Block",
    district: "Medak",
    state: "Telangana",
    date: "2025-04-30",
    duration: "3 weeks",
    skillLevel: "Beginner",
    maxParticipants: 25,
    enrolledCount: 0,
    rating: 4.3,
    description: "Eco-friendly basketry using wild grasses and palm leaves. A great introduction to traditional weaving.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Miniature Painting Masterclass",
    category: "Clay Art",
    trainerName: "Ramesh Kumawat",
    location: "Udaipur Art School",
    district: "Udaipur",
    state: "Rajasthan",
    date: "2025-08-15",
    duration: "12 weeks",
    skillLevel: "Advanced",
    maxParticipants: 5,
    enrolledCount: 0,
    rating: 5.0,
    description: "Learn the royal art of Rajput miniature painting. Focus on natural pigments and squirrel hair brushes.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Tie-Dye (Bandhani) Basics",
    category: "Handloom",
    trainerName: "Ramesh Kumawat",
    location: "Jamnagar Textile Hub",
    district: "Jamnagar",
    state: "Gujarat",
    date: "2025-06-12",
    duration: "3 weeks",
    skillLevel: "Beginner",
    maxParticipants: 30,
    enrolledCount: 0,
    rating: 4.2,
    description: "Discover the vibrant world of Bandhani. Learn tying patterns and natural dyeing processes.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Teak Wood Furniture Design",
    category: "Wood Carving",
    trainerName: "Ramesh Kumawat",
    location: "Mysore Carpentry Guild",
    district: "Mysore",
    state: "Karnataka",
    date: "2025-09-01",
    duration: "10 weeks",
    skillLevel: "Intermediate",
    maxParticipants: 10,
    enrolledCount: 0,
    rating: 4.7,
    description: "Build premium furniture using solid Mysore teak. Includes design theory and finishing techniques.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Metal Embossing Techniques",
    category: "Metal Craft",
    trainerName: "Ramesh Kumawat",
    location: "Moradabad Workshop",
    district: "Moradabad",
    state: "Uttar Pradesh",
    date: "2025-06-05",
    duration: "4 weeks",
    skillLevel: "Intermediate",
    maxParticipants: 10,
    enrolledCount: 0,
    rating: 4.7,
    description: "Traditional brass and copper embossing. Learn the ancient Nakshi art form from master craftsmen.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Madhubani Wall Art",
    category: "Clay Art",
    trainerName: "Ramesh Kumawat",
    location: "Madhubani Cultural Hut",
    district: "Madhubani",
    state: "Bihar",
    date: "2025-05-05",
    duration: "4 weeks",
    skillLevel: "Beginner",
    maxParticipants: 20,
    enrolledCount: 0,
    rating: 4.6,
    description: "Expression of nature and mythology through vibrant colors and geometric patterns.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Pashmina Wool Spinning",
    category: "Weaving",
    trainerName: "Ramesh Kumawat",
    location: "Ladakh Pashmina Center",
    district: "Leh",
    state: "Ladakh",
    date: "2025-10-10",
    duration: "12 weeks",
    skillLevel: "Advanced",
    maxParticipants: 6,
    enrolledCount: 0,
    rating: 4.8,
    description: "Learn to spin the finest wool in the world. This workshop supports high-altitude artisan communities.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Silver Filigree Art",
    category: "Metal Craft",
    trainerName: "Ramesh Kumawat",
    location: "Karimnagar Artisan Hub",
    district: "Karimnagar",
    state: "Telangana",
    date: "2025-11-01",
    duration: "8 weeks",
    skillLevel: "Advanced",
    maxParticipants: 8,
    enrolledCount: 0,
    rating: 4.9,
    description: "Master the delicate process of twisting fine silver wires into intricate artistic designs.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Terracotta Mural Art",
    category: "Clay Art",
    trainerName: "Ramesh Kumawat",
    location: "Bishnupur Cultural Center",
    district: "Bankura",
    state: "West Bengal",
    date: "2025-05-20",
    duration: "5 weeks",
    skillLevel: "Beginner",
    maxParticipants: 20,
    enrolledCount: 0,
    rating: 4.4,
    description: "Create stunning wall murals using terracotta. This course explores storytelling through clay relief work.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Organic Indigo Dyeing",
    category: "Handloom",
    trainerName: "Ramesh Kumawat",
    location: "Sangareddy Dye House",
    district: "Sangareddy",
    state: "Telangana",
    date: "2025-06-25",
    duration: "3 weeks",
    skillLevel: "Intermediate",
    maxParticipants: 18,
    enrolledCount: 0,
    rating: 4.5,
    description: "Learn the chemistry of natural fermentation indigo vats and various resist dyeing patterns.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Traditional Clay Sculpting",
    category: "Pottery",
    trainerName: "Ramesh Kumawat",
    location: "Nizamabad Pottery Center",
    district: "Nizamabad",
    state: "Telangana",
    date: "2025-08-01",
    duration: "6 weeks",
    skillLevel: "Beginner",
    maxParticipants: 15,
    enrolledCount: 0,
    rating: 4.3,
    description: "Work with local black clay to create functional and decorative pottery using traditional wheels.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Cane Basket Weaving",
    category: "Basket Weaving",
    trainerName: "Ramesh Kumawat",
    location: "Vikarabad Cane Works",
    district: "Vikarabad",
    state: "Telangana",
    date: "2025-09-15",
    duration: "4 weeks",
    skillLevel: "Beginner",
    maxParticipants: 22,
    enrolledCount: 0,
    rating: 4.5,
    description: "Learn to split cane and weave sturdy baskets and traditional lampshades.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Hand-Printed Textiles (Kalamkari)",
    category: "Handloom",
    trainerName: "Ramesh Kumawat",
    location: "Srikasasti Block",
    district: "Chittoor",
    state: "Andhra Pradesh",
    date: "2025-10-05",
    duration: "6 weeks",
    skillLevel: "Intermediate",
    maxParticipants: 14,
    enrolledCount: 0,
    rating: 4.7,
    description: "Ancient style of hand-painting or block-printing on cotton textile with vegetable dyes.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Dhokra Lamp Making",
    category: "Metal Craft",
    trainerName: "Ramesh Kumawat",
    location: "Secunderabad Art Studio",
    district: "Hyderabad",
    state: "Telangana",
    date: "2025-05-25",
    duration: "4 weeks",
    skillLevel: "Beginner",
    maxParticipants: 10,
    enrolledCount: 0,
    rating: 4.6,
    description: "A beginner-friendly introduction to tribal metal casting, focusing on creating decorative lamps.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Embroidered Wall Hangings",
    category: "Weaving",
    trainerName: "Ramesh Kumawat",
    location: "Khammam Textile Hub",
    district: "Khammam",
    state: "Telangana",
    date: "2025-07-15",
    duration: "5 weeks",
    skillLevel: "Intermediate",
    maxParticipants: 15,
    enrolledCount: 0,
    rating: 4.4,
    description: "Learn unique tribal embroidery styles from the Lambada community in Telangana.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Handmade Paper Craft",
    category: "Clay Art",
    trainerName: "Ramesh Kumawat",
    location: "Mahbubnagar Eco-Hub",
    district: "Mahbubnagar",
    state: "Telangana",
    date: "2025-11-10",
    duration: "2 weeks",
    skillLevel: "Beginner",
    maxParticipants: 30,
    enrolledCount: 0,
    rating: 4.8,
    description: "Create beautiful paper from agricultural waste and wildflower seeds.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Traditional Footwear (Jutti) Making",
    category: "Wood Carving",
    trainerName: "Ramesh Kumawat",
    location: "Mancherial Leather Lane",
    district: "Mancherial",
    state: "Telangana",
    date: "2025-06-01",
    duration: "8 weeks",
    skillLevel: "Advanced",
    maxParticipants: 10,
    enrolledCount: 0,
    rating: 4.6,
    description: "Master the art of handcrafted leather footwear with intricate silver and gold embroidery.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Handmade Glass Beads",
    category: "Metal Craft",
    trainerName: "Ramesh Kumawat",
    location: "Jangaon Craft Village",
    district: "Jangaon",
    state: "Telangana",
    date: "2025-09-20",
    duration: "4 weeks",
    skillLevel: "Intermediate",
    maxParticipants: 12,
    enrolledCount: 0,
    rating: 4.4,
    description: "Learn the art of flame-working glass to create beautiful, colorful tribal beads.",
    status: "approved",
    fee: "Free"
  },
  {
    title: "Traditional Folk Puppetry",
    category: "Wood Carving",
    trainerName: "Ramesh Kumawat",
    location: "Puppet Master Studio",
    district: "Rangareddy",
    state: "Telangana",
    date: "2025-12-05",
    duration: "6 weeks",
    skillLevel: "Intermediate",
    maxParticipants: 15,
    enrolledCount: 0,
    rating: 4.9,
    description: "Carve and paint traditional string puppets. Learn the history of shadow puppetry in South India.",
    status: "approved",
    fee: "Free"
  }
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB for seeding...');

    await User.deleteMany({});
    await Workshop.deleteMany({});
    await Category.deleteMany({});

    const createdUsers = await User.create(USERS);
    const ramesh = createdUsers.find(u => u.role === 'trainer');

    await Category.insertMany(CATEGORIES);

    const workshopsWithTrainer = WORKSHOPS.map(w => ({
      ...w,
      trainer: ramesh._id
    }));
    await Workshop.create(workshopsWithTrainer);

    console.log('✅ Database Seeded Successfully');
    process.exit();
  } catch (err) {
    console.error('❌ Seeding Error:', err);
    process.exit(1);
  }
};

seedDB();
